#!/usr/bin/env python3
"""Compile BOTH physical-output branches without claiming any board validation.

Input: CMake compile_commands.json generated by ARM GNU FW1 diagnostic build.
SYNTHETIC electrical values here are strictly compiler fixtures, NOT
production parameters, not board facts, and never linked or flashed.
"""
import json
import pathlib
import shlex
import subprocess
import sys

if len(sys.argv)!=2:
    raise SystemExit("usage: board_profile_compile_smoke.py BUILD_DIRECTORY")
build=pathlib.Path(sys.argv[1])
commands=json.loads((build/"compile_commands.json").read_text())
flags=[
    "-DAM13E_BOARD_POWER_STAGE_PROFILE=1",
    "-DAM13E_MOTOR_BOARD_DEADBAND_CONFIGURED=1",
    "-DAM13E_BOARD_PB13_ACTIVE_LEVEL=1",
    "-DAM13E_BOARD_GATE_PWM_INVERT_MASK=0",
    "-DAM13E_BOARD_OC_GPIO_PINCM=49",
    "-DAM13E_BOARD_OC_ACTIVE_LOW=1",
    "-DAM13E_BOARD_GATE_INPUTS_HIZ_SAFE=1",
    "-DAM13E_BOARD_GATE_DRIVER_HAS_HW_SHUTDOWN=1",
    "-DAM13E_MOTOR_DB_RED_TICKS=40",
    "-DAM13E_MOTOR_DB_FED_TICKS=40",
    "-DAM13E_MOTOR_DB_RED_POLARITY=0",
    "-DAM13E_MOTOR_DB_FED_POLARITY=1",
    "-DAM13E_MOTOR_DB_RED_INPUT=DL_MCPWM_DB_INPUT_PWMA",
    "-DAM13E_MOTOR_DB_FED_INPUT=DL_MCPWM_DB_INPUT_DB_RED",
    "-DAM13E_MOTOR_DB_SWAP_A=0",
    "-DAM13E_MOTOR_DB_SWAP_B=0",
    "-DAM13E_MOTOR_DB_COMPARE_OFFSET_TICKS=40",
    # Synthetic ADC numbers below exist ONLY to exercise compiler paths.
    "-DAM13E_BOARD_SENSORS_CONFIGURED=1",
    "-DAM13E_BOARD_ADC_FULLSCALE=4095",
    "-DAM13E_BOARD_ADC_VREF_MV=3300",
    "-DAM13E_BOARD_NTC_SUPPLY_MV=3300",
    "-DAM13E_BOARD_VBUS_TOP_OHMS=100000",
    "-DAM13E_BOARD_VBUS_BOTTOM_OHMS=10000",
    "-DAM13E_BOARD_NTC_MODEL=3",
]
targets={"motor_safety.c","motor_power_stage.c","motor_runtime_irq.c",
         "analog_runtime.c","main.c","util.c"}
observed=set()
for obj in commands:
    src=pathlib.Path(obj["file"]).name
    if src not in targets:
        continue
    # The project generates compile commands for many legacy ESC targets
    # and for BOOT5. NEVER inject AM13E board macros into STM32/Boot.
    if "CMakeFiles/AM13E.dir/" not in obj["command"]:
        continue
    observed.add(src)
    args=shlex.split(obj["command"])
    # An object-build command may include "-o PATH" and "-c".
    # Strip those: nothing produced by this smoke may be flashed.
    stripped=[]
    skip=False
    for word in args:
        if skip:
            skip=False
            continue
        if word=="-o":
            skip=True
            continue
        if word=="-c":
            continue
        stripped.append(word)
    result=subprocess.run(
        stripped+flags+["-Werror","-fsyntax-only"],
        cwd=obj["directory"],capture_output=True,text=True,check=False
    )
    sys.stdout.write(f"{src}: {'PASS' if result.returncode==0 else 'FAIL'}\n")
    if result.stdout: sys.stdout.write(result.stdout)
    if result.stderr: sys.stdout.write(result.stderr)
    if result.returncode: raise SystemExit(result.returncode)
if observed!=targets:
    raise SystemExit(f"Missing source(s) from compile database: {targets-observed}")
# The default compiled AM13E target has live Power Stage + DB + ADC.
# Positive branch above exercises explicit independent OC/OST2 wiring.
# A conflicting OC route must STILL fail at compile time (PB15=47).
safety=next((cmd for cmd in commands if
    pathlib.Path(cmd["file"]).name=="motor_power_stage.c" and
    "CMakeFiles/AM13E.dir/" in cmd["command"]), None)
if safety is None:
    raise SystemExit("Missing AM13E power-stage compile command")
args=shlex.split(safety["command"])
stripped=[]
skip=False
for word in args:
    if skip:
        skip=False
        continue
    if word=="-o":
        skip=True
        continue
    if word=="-c":
        continue
    stripped.append(word)
result=subprocess.run(stripped+[
    "-DAM13E_BOARD_OC_GPIO_PINCM=47",
    "-Werror","-fsyntax-only"],
    cwd=safety["directory"],capture_output=True,text=True,check=False)
if result.returncode==0 or (
   "Invalid/conflicting AM13E power-stage pin/level configuration"
   not in result.stderr):
    print(result.stdout+result.stderr)
    raise SystemExit("Conflicting independent OC pin was accepted")
print("PASS: default live Power Stage + ADC, synthetic OC/OST2 and invalid route")
print("PASS: 6 live branch compiler regression fixtures; NOT on-target proof")
