#!/usr/bin/env python3
"""Compile AM13E IO-only auxiliary feature profile and reject pin conflicts.

Only PB13/PB15 and previously mapped functions are physically selected
by the default Reference firmware. Optional OC, Serial TX and Current
Sense PINCM values in this test are SYNTHETIC, NOT a proposed PCB.
No file generated by this smoke is flashed.
"""
import json
import pathlib
import shlex
import subprocess
import sys

if len(sys.argv)!=2:
    raise SystemExit("usage: board_profile_compile_smoke.py BUILD_DIRECTORY")
build=pathlib.Path(sys.argv[1])
commands=json.loads((build/"compile_commands.json").read_text())

targets={"motor_safety.c","motor_power_stage.c","motor_runtime_irq.c",
         "analog_runtime.c","main.c","util.c","fault_input.c",
         "irq_vectors.c"}
observed={}

def syntax_check(obj,flags,should_pass=True,expected_error=None):
    args=shlex.split(obj["command"])
    stripped=[]
    skip=False
    for word in args:
        if skip:
            skip=False
            continue
        if word=="-o":
            skip=True
            continue
        if word=="-c":
            continue
        stripped.append(word)
    run=subprocess.run(stripped+flags+["-Werror","-fsyntax-only"],
                       cwd=obj["directory"],capture_output=True,text=True,
                       check=False)
    if bool(run.returncode==0)!=should_pass or (
        expected_error and expected_error not in run.stderr):
        print(run.stdout+run.stderr)
        raise SystemExit("Unexpected IO-only compile result for "+
                         pathlib.Path(obj["file"]).name+
                         ": "+str(flags))
    return run

for obj in commands:
    path=pathlib.Path(obj["file"])
    if path.name not in targets or "CMakeFiles/AM13E.dir/" not in obj["command"]:
        continue
    observed[path.name]=obj
    syntax_check(obj,[])
    print("PASS: default IO-only "+path.name)

if set(observed)!=targets:
    raise SystemExit("Missing reference FW1 sources "+str(targets-set(observed)))

# Exercise only physical pad-mode selection; never enable peripherals or
# use a synthetic PINCM number as an on-board design recommendation.
optional=[
    "-DAM13E_BOARD_OC_GPIO_PINCM=48",
    "-DAM13E_BOARD_SERIAL_TX_PINCM=49",
    "-DAM13E_BOARD_CURRENT_SENSE_PINCM=50"
]
syntax_check(observed["fault_input.c"],optional)
print("PASS: optional OC/Serial TX/Current pin modes compile")

syntax_check(observed["fault_input.c"],
             ["-DAM13E_BOARD_OC_GPIO_PINCM=47"],
             False,"Aux IO reservation conflicts")
syntax_check(observed["fault_input.c"],
             ["-DAM13E_BOARD_SERIAL_TX_PINCM=49",
              "-DAM13E_BOARD_CURRENT_SENSE_PINCM=49"],
             False,"Aux IO reservations must use distinct pins")
print("PASS: overlapping and reserved pin mappings rejected")

# Static non-operation checks: actual default firmware must not install
# a PB15 or OC trip, drive PB13 active, or enable nFAULT interrupts.
source_root=pathlib.Path(__file__).resolve().parents[3]
power=(source_root/"mcu/AM13E/motor_power_stage.c").read_text()
nfault=(source_root/"mcu/AM13E/fault_input.c").read_text()
runtime=(source_root/"mcu/AM13E/motor_safety.c").read_text()
vectors=(source_root/"mcu/AM13E/irq_vectors.c").read_text()
ref_cmake=(source_root/"CMakeLists.txt").read_text()
checks=[
    ("PB13 active enable", "gate_hold_inactive" in power and
     "am13e_power_stage_attach(" not in power and
     "am13e_power_stage_attach(" not in runtime),
    ("nFAULT IRQ", "DL_GPIO_enableInterrupt(" not in nfault and
     "am13e_app_nfault_asserted(" not in vectors),
    ("Fault Trip", "am13e_app_motor_nfault_trip_init(" not in runtime and
     '"/mcu/AM13E/motor_fault_route.c"' not in ref_cmake),
    ("Independent OC", "DL_XBAR_selectPWMXBARSource(" not in power),
    ("GPIO-only serial", "DL_GPIO_initDigitalInput(AM13E_BOARD_SERIAL_TX_PINCM)" in nfault),
    ("Analog-only current sense", "DL_GPIO_initPeripheralAnalogFunction(AM13E_BOARD_CURRENT_SENSE_PINCM)" in nfault)
]
for name,passed in checks:
    if not passed:
        raise SystemExit("IO-only non-operation contract failed: "+name)
    print("PASS: "+name+" IO-only")
